# hi this is my first python program
print ("hello world!")
print(4+5)
print(4-5)
print(4*5)
print(40/5)
print(2**5)
print(2**-3)
print(4**(1/3))
print(14//3)
print(50%3)
print("hi","hello", " hallo", 5)
print('hi user, please enter a number')
x = input()
print ("your number is :", x)
print("hi please enter your name :")
name = input()
print("and your last name: ")
lastname = input()
print( "hello ", name + lastname )
print("hi please enter your first number ")
b = int(input( ))
print("and now please enter your second number ")
c= int(input())
z = b*c
print(z)
print( " enter a float number ")
o = float(input())
p = o+1
print(p)
print("do you want see a magic? than enter a number and set 0 at first of that")
q = int(input())
print("your number is here",q) 
print(" do you want to see that your number is a multiple or not? so please enter your number ")
w = int(input())
if w % 2 == 0:
    print("YES, It is a multiple of 2")
else:
    print("NO, It is a multiple of 2")
    
print(" goodbye this is the end")